# lambda функция, работа с исключениями

# lambda_func = lambda num1, num2: num1 + num2
# print(lambda_func(2, 3))

# def nums(num1, num2):
#     return num1 + num2
# print(nums(5, 5))


# def up_letter(word: str):
#     return word.title()

# def show_words(func, list_words):
#     for i in list_words:
#         print(func(i))

# show_words(up_letter, ['bishkek', 'naryn', 'osh'])

# map, filter
# filtered_nums = list(filter(lambda num: num > 9, nums))
# print(filtered_nums)

# nums = list(range(1, 16))
# print(nums)
# mapped_nums = tuple(map(lambda num: num + 5, nums))
# print(mapped_nums)

try:
    code
except:
    code
    message
finally:
    message

